# Generated by Django 5.1.1 on 2024-11-14 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_detectedobject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_image', models.ImageField(upload_to='detected/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('detection_result', models.TextField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
            ],
        ),
        migrations.DeleteModel(
            name='DetectedObject',
        ),
    ]
